### ISSUE TITLE
Do you think this configuration would work with use-package?

### ISSUE THREAD

**Issue by alienbogart** [belak/dotfiles#1]
Saw your post on reddit about. I was trying to use org-dotemacs, but your solution is both simpler and better.

**Comment by belak** [comment]
Glad you find it useful! I use the built in org package so my setup configures use-package and the package repos in the README.org file. Is there anything specific you haven’t been able to get to work? There is a chance that the loading of use-package is out of date since I haven’t updated this in a while.
